spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baohulu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
  kafka:
    bootstrap-servers: 192.168.136.132:9092
    consumer:
      properties:
        group.id: defaultConsumerGroup
logging:
  level:
    org:
      apache:
        kafka:
          clients: error
